-- Generated by nwg-displays on 2026-06-16 at 16:12:52. Do not edit manually.
---@diagnostic disable: undefined-global
hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.02",
    position = "0x0",
    scale = 0.9999999999999999
})
