package.path = "./?.lua;" .. package.path

local config = require("config")
local h = require("lib")

local p = config.paths

local function mkdir(path)
  os.execute(string.format("mkdir -p %q", path))
end

local function render(name)
  return h.lines(require(name))
end

mkdir(p.generated)

h.write_file(p.generated .. "/defaults.conf", render("defaults"))
h.write_file(p.generated .. "/startup.conf", render("startup"))
h.write_file(p.generated .. "/settings.conf", render("settings"))
h.write_file(p.generated .. "/decorations.conf", render("decorations"))
h.write_file(p.generated .. "/animations.conf", render("animations"))
h.write_file(p.generated .. "/keybinds.conf", render("keybinds"))
h.write_file(p.generated .. "/windowrules.conf", render("windowrules"))
h.write_file(p.generated .. "/monitors.conf", render("monitors"))
h.write_file(p.generated .. "/workspaces.conf", "# Add workspace rules here.\n")

h.write_file(p.generated .. "/hyprland.conf", h.lines({
  h.comment("Generated by ~/.config/hypr/hyrpland_lua/emit.lua"),
  h.exec_once("$HOME/.config/hypr/initial-boot.sh"),
  h.blank(),
  h.source(p.generated .. "/defaults.conf"),
  h.source(p.configs .. "/ENVariables.conf"),
  h.source(p.user_configs .. "/ENVariables.conf"),
  h.source(p.generated .. "/startup.conf"),
  h.source(p.configs .. "/Laptops.conf"),
  h.source(p.user_configs .. "/Laptops.conf"),
  h.source(p.user_configs .. "/LaptopDisplay.conf"),
  h.source(p.configs .. "/WindowRules.conf"),
  h.source(p.generated .. "/windowrules.conf"),
  h.source(p.generated .. "/settings.conf"),
  h.source(p.generated .. "/decorations.conf"),
  h.source(p.generated .. "/animations.conf"),
  h.source(p.generated .. "/keybinds.conf"),
  h.source(p.generated .. "/monitors.conf"),
  h.source(p.generated .. "/workspaces.conf"),
}))

print("Generated Hyprland Lua profile in " .. p.generated)
