# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(2A2833)
$foreground = rgb(CDEBEB)
$color0 = rgb(504D59)
$color1 = rgb(55354C)
$color2 = rgb(4C4C64)
$color3 = rgb(35547F)
$color4 = rgb(72727C)
$color5 = rgb(7F7F84)
$color6 = rgb(559495)
$color7 = rgb(B0DADA)
$color8 = rgb(7B9899)
$color9 = rgb(714766)
$color10 = rgb(666586)
$color11 = rgb(4770A9)
$color12 = rgb(9898A5)
$color13 = rgb(A9A9B0)
$color14 = rgb(71C5C6)
$color15 = rgb(B0DADA)
