# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(070007)
$foreground = rgb(E9EAC8)
$color0 = rgb(0C030C)
$color1 = rgb(463048)
$color2 = rgb(4A553A)
$color3 = rgb(A25671)
$color4 = rgb(A47A6D)
$color5 = rgb(788DAE)
$color6 = rgb(90924A)
$color7 = rgb(D7D8A9)
$color8 = rgb(969776)
$color9 = rgb(5D4060)
$color10 = rgb(63714D)
$color11 = rgb(D87297)
$color12 = rgb(DBA391)
$color13 = rgb(A0BCE8)
$color14 = rgb(C0C263)
$color15 = rgb(D7D8A9)
