# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(0D0003)
$foreground = rgb(F1F1F3)
$color0 = rgb(0D0003)
$color1 = rgb(4A2136)
$color2 = rgb(323656)
$color3 = rgb(323656)
$color4 = rgb(8F455B)
$color5 = rgb(626895)
$color6 = rgb(A2A1A6)
$color7 = rgb(E3E3E6)
$color8 = rgb(9F9FA1)
$color9 = rgb(632C48)
$color10 = rgb(434872)
$color11 = rgb(434872)
$color12 = rgb(BF5C7A)
$color13 = rgb(838BC7)
$color14 = rgb(D8D7DD)
$color15 = rgb(E3E3E6)
