-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */
-- Decoration Settings
-- https://wiki.hypr.land/Configuring/Basics/Variables/#decoration
---@diagnostic disable: undefined-global

local home = assert(os.getenv("HOME"), "HOME environment variable is not set")

-- Colors generated by wallust. The file is rewritten by ThemeChanger.sh, so it
-- is read at config load instead of being copied into Lua.
local wallust = require("hyprvars").read(home .. "/.config/hypr/wallust/wallust-hyprland.conf")

local function color(name, fallback)
    return wallust[name] or fallback
end

hl.config({
    general = {
        border_size = 2,
        gaps_in = 3,
        gaps_out = 3,

        col = {
            active_border = color("color12", "rgba(33ccffee)"),
            inactive_border = color("color10", "rgba(595959aa)"),
        },
    },

    decoration = {
        rounding = 6,

        active_opacity = 1.0,
        inactive_opacity = 0.9,
        fullscreen_opacity = 1.0,

        dim_inactive = true,
        dim_strength = 0.1,
        dim_special = 0.8,

        shadow = {
            enabled = true,
            range = 3,
            render_power = 1,

            color = color("color12", "rgba(1a1a1aee)"),
            color_inactive = color("color10", "rgba(1a1a1aee)"),
        },

        blur = {
            enabled = true,
            size = 15,
            passes = 3,
            new_optimizations = true,
            xray = true,
            ignore_opacity = true,
            special = true,
            popups = true,
            noise = 0.09,
        },
    },

    group = {
        col = {
            border_active = color("color15", "rgba(33ccffee)"),
        },

        groupbar = {
            col = {
                active = color("color0", "rgba(1a1a1aee)"),
            },
        },
    },
})
