$mainMod = SUPER
$scriptsDir = /home/azaz/.config/hypr/scripts
$UserScripts = /home/azaz/.config/hypr/UserScripts
$UserConfigs = /home/azaz/.config/hypr/UserConfigs

# Common shortcuts
bindd = $mainMod, D, app launcher, exec, pkill rofi || true && rofi -show drun -modi drun,filebrowser,run,window
bindd = $mainMod, B, open default browser, exec, xdg-open "https://"
bindd = $mainMod, A, desktop overview, exec, $scriptsDir/OverviewToggle.sh
bindd = $mainMod, Return, Open terminal, exec, $term
bindd = $mainMod, E, file manager, exec, $files

# Wallpaper and theme
bindd = $mainMod, T, Global theme switcher using Wallust, exec, $scriptsDir/ThemeChanger.sh
bindd = $mainMod, W, select wallpaper, exec, $UserScripts/WallpaperSelect.sh
bindd = $mainMod SHIFT, W, wallpaper effects, exec, $UserScripts/WallpaperEffects.sh
bindd = CTRL ALT, W, random wallpaper, exec, $UserScripts/WallpaperRandom.sh

# Window controls
bindd = $mainMod SHIFT, F, fullscreen, fullscreen
bindd = $mainMod CTRL, F, maximize window, fullscreen, 1
bindd = $mainMod, SPACE, Float current window, togglefloating
bindd = $mainMod, Q, close active window, killactive
bindd = $mainMod SHIFT, Q, Terminate active process, exec, $scriptsDir/KillActiveProcess.sh

# System
bindd = CTRL ALT, Delete, exit Hyprland, exec, hyprctl dispatch exit 0
bindd = CTRL ALT, L, lock screen, exec, $scriptsDir/LockScreen.sh
bindd = CTRL ALT, P, powermenu, exec, $scriptsDir/Wlogout.sh

# Focus
bindd = $mainMod, left, focus left, movefocus, l
bindd = $mainMod, right, focus right, movefocus, r
bindd = $mainMod, up, focus up, movefocus, u
bindd = $mainMod, down, focus down, movefocus, d

# Workspaces
bindd = $mainMod, tab, next workspace, workspace, m+1
bindd = $mainMod SHIFT, tab, previous workspace, workspace, m-1
bindd = $mainMod, code:10, workspace 1, workspace, 1
bindd = $mainMod, code:11, workspace 2, workspace, 2
bindd = $mainMod, code:12, workspace 3, workspace, 3
bindd = $mainMod, code:13, workspace 4, workspace, 4
bindd = $mainMod, code:14, workspace 5, workspace, 5
bindd = $mainMod, code:15, workspace 6, workspace, 6
bindd = $mainMod, code:16, workspace 7, workspace, 7
bindd = $mainMod, code:17, workspace 8, workspace, 8
bindd = $mainMod, code:18, workspace 9, workspace, 9
bindd = $mainMod, code:19, workspace 10, workspace, 10

# Mouse
bindmd = $mainMod, mouse:272, move window, movewindow
bindmd = $mainMod, mouse:273, resize window, resizewindow
